export const projects = [
  // {
  //     id: 1,
  //     image: '/images/quotes.png',
  //     title: 'random quotes generator',
  //     description: 'API generated random quotes with preloader',
  //     category: 'javascript',
  //     url: 'https://vibrant-visvesvaraya-8c3b76.netlify.app/',
  //     code: 'https://github.com/wavyadri/freeCodeCamp-Basic-JavaScript/tree/main/projects/front%20end%20libraries/random%20quote%20js',
  // },
  {
    id: 2,
    image: '/images/wealthify.png',
    title: 'Wealthify - stocks/crypto trading simulation',
    description:
      'Live financial API data, buy/sell simulation, Rails API backend',
    category: 'react',
    code: 'https://github.com/wavyadri/wealthify',
  },
  {
    id: 8,
    image: '/images/tweeter.png',
    title: 'Tweeter App, a twitter clone',
    description: 'User generated tweets posted to a feed with AJAX',
    category: 'Node/Express',
    code: 'https://github.com/wavyadri/tweeter',
  },
  // {
  //     id: 3,
  //     image: '/images/cocacola.png',
  //     title: 'product website',
  //     description: 'product feature page with image slider',
  //     category: 'HTML/CSS',
  //     url: 'https://silly-panini-ba6b31.netlify.app/',
  //     code: 'https://github.com/wavyadri/Coca-Cola-Website',
  // },
  {
    id: 4,
    image: '/images/netflix.png',
    title: 'subscription service website',
    description: 'subscription service landing page',
    category: 'HTML/CSS',
    url: 'https://inspiring-swartz-c96988.netlify.app/',
    code: 'https://github.com/wavyadri/Netflix-Landing-Page-Website',
  },
  {
    id: 5,
    image: '/images/loruki.png',
    title: 'web services website',
    description: '3 page website with form',
    category: 'HTML/CSS',
    url: 'https://angry-brown-2c67f4.netlify.app/',
    code: 'https://github.com/wavyadri/Loruki-Website',
  },
  //   {
  //     id: 6,
  //     image: '/images/sign-up.png',
  //     title: 'sign up form',
  //     description: 'form validation and error counter',
  //     category: 'javascript',
  //     url: 'https://vibrant-clarke-f8afc0.netlify.app/',
  //     code: 'https://github.com/wavyadri/JS-Projects/tree/main/FORMS/Form%20Validation',
  //   },
  //   {
  //     id: 7,
  //     image: '/images/shopping-list.png',
  //     title: 'shopping list',
  //     description: 'CRUD list with JSON server',
  //     category: 'javascript',
  //     url: 'https://distracted-hawking-24a274.netlify.app/',
  //     code: 'https://github.com/wavyadri/JS-Projects/tree/main/LISTS/Shop%20List%202.0',
  //   },
  {
    id: 9,
    image: '/images/eat-app.png',
    title: 'meal delivery app',
    description: 'meal delivery mobile app',
    category: 'UX',
    url: 'https://xd.adobe.com/view/f6c355e4-9d72-4d73-ba84-506f5e4ced4c-a390/?fullscreen',
  },
  {
    id: 10,
    image: '/images/hike.png',
    title: 'hiking website',
    description: 'multi page website',
    category: 'UX',
    url: 'https://xd.adobe.com/view/1c2e4d6c-afe0-467c-9fbb-8c42897cfa07-497d/?fullscreen',
  },
  {
    id: 11,
    image: '/images/wine.png',
    title: 'wine shop',
    description: 'e-commerce product slider',
    category: 'UX',
    url: 'https://xd.adobe.com/view/310ae8a0-c2e1-4e36-8dc7-f44d77a626e7-6459/?fullscreen',
  },
  {
    id: 12,
    image: '/images/colour.png',
    title: 'web services website',
    description: 'gradient mobile responsive website',
    category: 'HTML/CSS',
    url: 'https://unruffled-hawking-638cce.netlify.app/',
    code: 'https://github.com/wavyadri/Colours-Website',
  },
  {
    id: 13,
    image: '/images/cocktails.png',
    title: 'cocktail API search with react',
    description: 'API generated search bar with react router',
    category: 'react',
    url: 'https://happy-meninsky-63ab5d.netlify.app/',
    code: 'https://github.com/wavyadri/cocktail-search',
  },
  {
    id: 14,
    image: '/images/pizza-maker.png',
    title: 'custom pizza maker with shopping cart in react',
    description: 'Custom topping picker with useReducer checkout cart',
    category: 'react',
    url: 'https://hardcore-tereshkova-ed717b.netlify.app/',
    code: 'https://github.com/wavyadri/pizza-maker',
  },
  {
    id: 15,
    image: '/images/tinyapp.png',
    title: 'TinyApp - a bit.ly clone',
    description: 'HTTP server which allows logged in users to shorten URLs',
    category: 'Node/Express',
    code: 'https://github.com/wavyadri/tinyapp',
  },
  {
    id: 16,
    image: '/images/scheduler.png',
    title: 'Scheduling app to book or cancel interviews',
    description:
      'Book or cancel interviews with Jest, Cypress & Storybook testing',
    category: 'react',
    code: 'https://github.com/wavyadri/Scheduler',
  },
  {
    id: 17,
    image: '/images/gift_guide.png',
    title: 'Gift Guide',
    description: 'CRUD Gift List and Reviews with PERN Stack',
    category: 'Node/Express',
    code: 'https://github.com/wavyadri/gift_guide',
  },
];
